version: '3'
services:
  traefik:
    image: "traefik:v2.2"
    container_name: "traefik-final"
    command: 
      - --web
      - --docker
      - --docker.domain=docker.localhost
      - --api.insecure=true 
      # Docker
      - --providers.docker 
      - --entrypoints.web.address=:80
      - --docker.exposedbydefault=false
    networks:
      - traefik-global-proxy
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - "./traefik.toml:/etc/traefik/traefik.toml"
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
  whoami:
    image: "traefik/whoami"
    container_name: "whoami-final"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`vargabalazs.syscops.com`)"
      - "traefik.http.routers.whoami.entrypoints:=web"     
  web:
    container_name: weather-final
    networks:
      - traefik-global-proxy
    labels: 
      - "traefik.enable=true"
      - "traefik.backend=traefik"
      - "traefik.frontend.rule=Host:vargabalazs.syscops.com"
      - "traefik.http.routers.simple-fe.rule=Host(`vargabalazs.syscops.com`)" # domain to expose on
      - "traefik.http.routers.simple-fe.entrypoints=websecure"
      - "traefik.http.routers.simple-fe.tls.certresolver=letsencrypt"
    build:
      context: ./
    volumes:
      - .:/app
    command: npm start
    ports:
      - "3000:3000"

networks:
   traefik-global-proxy:
      external: true  