[entryPoints.http]
address = ":80"
[entryPoints.http.redirect]
entryPoint = "https"
[entryPoints.https]
address = ":443"
[entryPoints.https.tls]

[http.routers]
  [http.routers.Router-1]
    # By default, routers listen to every entry points
    rule = "Host(`http://vargabalazs.syscops.com/`)"
    service = "web"

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "vargabalazs.syscops.com"
watch = true
exposedbydefault = false
network="traefik-global-proxy"

[acme]
email = "vargabalazs0202@gmail.com.com"
storage = "acme.json"
entryPoint = "https"
OnHostRule = true
  [acme.httpChallenge]
  entryPoint = "http"